New cache config API
firebase/firebase-android-sdk pull request #4869
Opened 2023-04-06 16:38 UTC by wu-hui

2023-04-12 16:01 UTC, tom-andersen requested changes

2023-04-12 16:01 UTC, tom-andersen commented on firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
> +    public Builder setLocalCacheSettings(@NonNull LocalCacheSettings settings) {
All other properties have corresponding get method. I would expect this to have a default value of `PersistentCacheSettings`, just like other properties have default values.

2023-04-13 18:27 UTC, wu-hui reviewed
Thanks for the review.

2023-04-13 20:21 UTC, tom-andersen commented on firebase-firestore/api.txt
> +    method @NonNull public com.google.firebase.firestore.LocalCacheSettings getCacheSettings();
Since there isn't any complexity of default values, and I am fine with that.

2023-04-13 20:34 UTC, tom-andersen commented on firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
> +  public LocalCacheSettings getCacheSettings() {
My small corner case concern would be customers building upon this behavior. 

However, removing the deprecated methods will be a breaking change anyway, so changing the semantics slightly at that time seems perfectly fine.

2023-04-13 20:44 UTC, tom-andersen commented on firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
> +    public Builder setLocalCacheSettings(@NonNull LocalCacheSettings settings) {
This does avoid problems and can easily be added later if we change our minds.

2023-04-14 14:59 UTC, merged