Update AGP to version 7.3.1
firebase/firebase-android-sdk pull request #5114
Opened 2023-06-27 04:38 UTC by rlazo

2023-06-29 16:28 UTC, emilypgoogle requested changes
I may have missed something but I tried to make sure all the package names were properly moved to the right place and it looks good. There are some minor indentation issues, and I noticed the placing of the `namespace` attribute is inconsistently before `compiledSdkVersion`. I don't know if that much matters, our build.gradles seem to be in a perpetual state of inconsistent disarray, but I thought I'd mention it.

2023-06-29 22:11 UTC, rlazo commented on protolite-well-known-types/protolite-well-known-types.gradle
> +        task.addIncludeDir(files('fix-javalite/proto'))
Fixed

2023-06-29 22:14 UTC, rlazo commented
> I may have missed something but I tried to make sure all the package names were properly moved to the right place and it looks good. There are some minor indentation issues, and I noticed the placing of the `namespace` attribute is inconsistently before `compiledSdkVersion`. I don't know if that much matters, our build.gradles seem to be in a perpetual state of inconsistent disarray, but I thought I'd mention it.

I've moved the namespace declaration to be on top of compileSdk consistently. Definitely, our build.gradle files are in need of some clean up to be more consistent, but I think it's OK for now.

2023-06-30 15:45 UTC, emilypgoogle approved these changes
Single style concern, otherwise everything seems consistently organized and well laid out :+1: all good by me

2023-06-30 15:45 UTC, emilypgoogle commented on protolite-well-known-types/protolite-well-known-types.gradle
> +	        task.addIncludeDir(files('fix-javalite/proto'))
Looks like this got overindented now?

2023-06-30 15:47 UTC, merged