Remove non link brackets from release notes
firebase/firebase-android-sdk pull request #5737
Opened 2024-02-23 20:29 UTC by daymxn

Per [b/326629027](https://b.corp.google.com/issues/326629027),

This adds a transformation in our release notes to separate brackets from their content if they're not wrapping a link. This is to avoid propagating the content to the release notes, as it shouldn't be there. In the future, we may want to add some warning for instances found (as they may have been intended to be links).

2024-02-23 22:43 UTC, emilypgoogle requested changes

2024-02-23 22:43 UTC, emilypgoogle commented on buildSrc/src/main/java/com/google/firebase/gradle/plugins/MakeReleaseNotesTask.kt
> +    private val NON_LINK_BRACKETS_REGEX = Regex("\\[(.+?)](?!\\()", RegexOption.MULTILINE)
This regex will match `[foo](bar.baz) lorem ipsum [qud]` and could be adjusted to not match `]` characters outside of the terminating one.

2024-02-24 00:47 UTC, rlazo commented
In (most)? cases, what we want is the reference to be transformed from [[app_check]] to {{app_check}}, see https://github.com/firebase/firebase-android-sdk/blob/master/appcheck/firebase-appcheck-debug/CHANGELOG.md and cl/605317607 rather than removed

2024-02-28 21:19 UTC, rlazo commented
@rachelsaunders does tooling break or complains if an unknown value is present inside the double brackets? e.g. {{notaname}}, does it complain/break or silently drops it?

2024-02-28 21:27 UTC, rachelsaunders commented
> @rachelsaunders does tooling break or complains if an unknown value is present inside the double brackets? e.g. {{notaname}}, does it complain/break or silently drops it?


If the contents within the double curly braces is not a valid string, our internal staging/build tooling will error (and maybe even break the build).  It won't just silently drop it.  So, if the string happens to be wrong here in the changelog and thus the conversion into the internal systems, we'll be able to easily catch it downstream _before_ it goes to prod.

2024-02-28 22:22 UTC, rlazo commented
> > @rachelsaunders does tooling break or complains if an unknown value is present inside the double brackets? e.g. {{notaname}}, does it complain/break or silently drops it?
> 
> If the contents within the double curly braces is not a valid string, our internal staging/build tooling will error (and maybe even break the build). It won't just silently drop it. So, if the string happens to be wrong here in the changelog and thus the conversion into the internal systems, we'll be able to easily catch it downstream _before_ it goes to prod.

That's what I was hoping for, thanks!

2024-12-06 20:41 UTC, closed without merging