Fix timezone calculation in Timestamp
firebase/firebase-android-sdk pull request #6038
Opened 2024-06-15 00:17 UTC by cherylEnkidu

2024-06-15 01:15 UTC, cherylEnkidu commented on firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializer.kt
> -      "Value does not conform to the RFC3339 specification (str=$str)"
RFC3339 supports more than 9 digits in time-secfrac, so what is allowed by Firebase is not 100% RFC3339

2024-06-17 14:27 UTC, dconeybe requested changes
Thanks for the fix! That's a pretty serious bug. 

Please add a release notes entry to https://github.com/firebase/firebase-android-sdk/blob/eb735a5cd09bb999e9a9444de9a4cf75787ca9d9/firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt#L83

2024-06-17 14:27 UTC, dconeybe commented on firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializer.kt
> +    require(strUppercase.matches(regex)) { "Timestamp string: (str=$str) format doesn't support." }
This updated error message is less actionable than the old one, as it doesn't give any hints as to what the problem was. If the only digression from RFC3339 is arbitrary sub-second support, then maybe we could just change the old message to something like this:

> Value does not conform to the RFC3339 specification with up to 9 digits of sub-second precision (str=$str)

What do you think?

See go/error-message-best-practices

2024-06-17 18:03 UTC, dconeybe approved these changes

2024-06-17 18:03 UTC, dconeybe commented
Thanks for the fix!

2024-06-18 18:13 UTC, merged