[DRAFT] Revamp Schema declaration
firebase/firebase-android-sdk pull request #6258
Opened 2024-09-13 23:08 UTC by rlazo

2024-09-16 20:05 UTC, rachelsaunders requested changes

2024-09-16 20:05 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * @param format: Pattern that values need to adhere to
```suggestion
     * @param format: The pattern that values need to adhere to
```

2024-09-16 20:05 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * Returns a schema for a complex object. In a function it will be returned as a [JSONObject]
```suggestion
     * Returns a schema for a complex object. In a function, it will be returned as a [JSONObject].
```

2024-09-16 20:05 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * @param properties: Map of the fields of the object to their schema
```suggestion
     * @param properties: The map of the object's fields to their schema
```

2024-09-16 21:38 UTC, rachelsaunders approved these changes

2024-09-17 03:58 UTC, rlazo commented
@daymxn @davidmotson friendly ping

2024-09-17 21:29 UTC, rlazo commented
@daymxn @davidmotson friendly ping

2024-09-18 17:02 UTC, daymxn approved these changes
Leaving offline discussion here for context:

Ideally we'd use a more kotliny approach, but since that would require overhead we don't currently have- this approach should be fine for now; ensuring we align with other SDKs.

2024-09-19 18:57 UTC, merged