Improved refdocs for Schema
firebase/firebase-android-sdk pull request #6420
Opened 2024-10-31 15:49 UTC by rlazo

The improvements include:

- Clarify that `integer` and `float` types are hints to the model, and the returned data could potentially overflow the respective native types.
- Include missing parameters for some of the functions.
- Add examples for `enumerations` and `obj`.

2024-10-31 15:50 UTC, rlazo commented
cc @andrewheard

2024-10-31 18:32 UTC, emilypgoogle approved these changes

2024-10-31 21:31 UTC, rachelsaunders requested changes

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> + * the results.
```suggestion
 * **Note:** While optional, including a `description` field in your `Schema` is strongly
 * encouraged. The more information the model has about what it's expected to generate, the better
 * the results.
```

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * that decoding it as an `Int` variable, `int` in Java, could overflow.
```suggestion
     * that decoding it as an `Int` variable (or `int` in Java) could overflow.
```

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * Therefore it's *possible* that decoding it as a `Float` variable, `float` in Java, could
```suggestion
     * Therefore it's *possible* that decoding it as a `Float` variable (or `float` in Java) could
```

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * **Example:** A `City` could be represented with the following object `Schema`.
```suggestion
     * **Example:** A `city` could be represented with the following object `Schema`.
```

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * @param description An optional description of what the array represent.
```suggestion
     * @param item The [Schema] of the elements of stored in the array.
     * @param description An optional description of what the array represents.
```

2024-10-31 21:31 UTC, rachelsaunders commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * @param item The [Schema] of the elements of stored in the array.
```suggestion
     * @param item The [Schema] of the elements stored in the array.
```

2024-11-01 14:14 UTC, rlazo commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
> +     * @param description An optional description of what the array represent.
Edited manually to match suggestion.

2024-11-01 15:51 UTC, rachelsaunders submitted a review, later dismissed

2024-11-01 15:51 UTC, rachelsaunders commented on firebase-vertexai/CHANGELOG.md
> +* [fixed] Clarified in kdocs that `Schema.integer` and `Schema.float` only provide hints to the model. (#6420)
```suggestion
* [fixed] Clarified in the documentation that `Schema.integer` and `Schema.float` only provide hints to the model. (#6420)
```

2024-11-01 16:08 UTC, rachelsaunders approved these changes

2024-11-01 16:13 UTC, merged