Extend Firebase SDK with new APIs to consume streaming callable function response
firebase/firebase-android-sdk pull request #6602
Opened 2024-12-16 22:03 UTC by MustafaJadid2025

Extend Firebase SDK with new APIs to consume streaming callable function response.

- Handling the server-sent event (SSE) parsing internally
- Providing proper error handling and connection management
- Maintaining memory efficiency for long-running streams

2025-02-11 15:30 UTC, rlazo commented
is this PR ready for review? please assign @emilypgoogle and myself as reviewers as soon as it's ready. Thanks

2025-02-11 21:35 UTC, MustafaJadid2025 reviewed
The PR is ready for review.

2025-02-12 17:59 UTC, emilypgoogle requested changes

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/api.txt
> +    method @NonNull public org.reactivestreams.Publisher stream(@Nullable Object data = null);
Merge in main and regenerate the api.txt file for v3

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +  private class PublisherStream(
Best to move this out to an internal class

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +        Preconditions.checkNotNull(url, "url cannot be null")
Preconditions for initialization should be in the initializer, this will downstream errors in obscure ways.

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +              val message: String
Why store `message`? All implementations just get the message from the `code.name`

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +                line.startsWith("result:") -> line.removePrefix("result:")
Does removing the `data:` and `result:` prefixes affect the ability to parse whether a response is a message or result below?

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +  /** Called when a new event is received. */
Phrasing is a bit odd here, messages aren't really "called". Would also be best to document concisely the difference between a message and a result so that users don't confuse a "result" with the last message

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/androidTest/java/com/google/firebase/functions/StreamTests.kt
> +class StreamTests {
None of these tests distinguish messages and results, should there be additional testing verifying the behavior we expect?

2025-02-12 17:59 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&lt;?&gt;][java.util.List], where the contained objects are also one of these types.
Are these escape codes what renders properly as angle brackets in kdocs?

2025-02-12 20:18 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +        Preconditions.checkNotNull(url, "url cannot be null")
We placed the `Precondition` at the very beginning of the `call` method inside the FirebaseFunctions.kt. I'll make the same placement for the` stream` method.

2025-02-12 20:19 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +  private class PublisherStream(
I'll make it as an internal class.

2025-02-12 20:26 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +              val message: String
I referred the code from the `call` method. However, `code.name` is better. I'll make changes.

2025-02-12 20:34 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +                line.startsWith("result:") -> line.removePrefix("result:")
Yes. From the compatibility perspective we need to check the `result` prefix.  BTW I referred the vertexai ktor to retrieve the message or result.

2025-02-12 20:47 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +  /** Called when a new event is received. */
I’ve updated the KDoc to clarify the distinction between Message and Result, making it explicit that:

Message represents an intermediate event sent via response.write().
Result represents the final response that terminates the stream.

2025-02-12 21:04 UTC, thatfiredev commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +public sealed class StreamResponse(public open val data: Any) {
sealed classes are discouraged for public APIs because changing these APIs can cause source and binary incompatibility. (read more in the [internal guide](http://go/androidx-api-guidelines#exhaustive-when))

An alternative to this would be an abstract class with a private constructor:

```kotlin
abstract class StreamResponse private constructor(public open val data: Any) {
  public class Message(override val data: Any) : StreamResponse(data)
  public class Result(override val data: Any) : StreamResponse(data)
}
```

2025-02-12 21:07 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&lt;?&gt;][java.util.List], where the contained objects are also one of these types.
After reviewing the call method, I found some discrepancies and applied the same escape codes that we used in the call method.

2025-02-12 21:14 UTC, MustafaJadid2025 commented on firebase-functions/api.txt
> +    method @NonNull public org.reactivestreams.Publisher stream(@Nullable Object data = null);
Thanks, Emily! I’ve merged the latest changes from main. Could you clarify which script or command I should run to regenerate the api.txt file for v3? Let me know, and I'll get it updated right away.

2025-02-12 21:34 UTC, MustafaJadid2025 commented on firebase-functions/src/androidTest/java/com/google/firebase/functions/StreamTests.kt
> +class StreamTests {
I embedded the distinction in test cases in the upcoming commit.

2025-02-12 21:47 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +public sealed class StreamResponse(public open val data: Any) {
Thanks. I applied the changes.

2025-02-19 07:32 UTC, rlazo requested changes
I tried running the tests, after installing them in a project I own, and I couldn't get any of them to pass. They all fail as if no data was send from the server (empty `onNextList`). 

For reference, I could verify in the Console that the functions were successfully being executed, (http 200).

2025-02-19 07:32 UTC, rlazo commented on firebase-functions/src/androidTest/backend/functions/index.js
> +      response.write({chunk});
don't you need `sendChunk`?

https://firebase.google.com/docs/functions/callable?_gl=1*e2jcaw*_up*MQ..*_ga*MjAzMTIzMzMxNS4xNzM5OTQ5OTQz*_ga_CW55HF8NVT*MTczOTk0OTk0Mi4xLjAuMTczOTk0OTk0Mi4wLjAuMA..&gen=2nd#stream-back

2025-02-19 16:22 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +package com.google.firebase.functions
Done.

2025-02-19 20:36 UTC, MustafaJadid2025 commented
> I tried running the tests, after installing them in a project I own, and I couldn't get any of them to pass. They all fail as if no data was send from the server (empty `onNextList`).
> 
> For reference, I could verify in the Console that the functions were successfully being executed, (http 200).

I made changes on the index.js and the test files. The command `./gradlew :firebase-functions:connectedCheck` passed.

2025-02-19 20:38 UTC, MustafaJadid2025 commented on firebase-functions/src/androidTest/backend/functions/index.js
> +      response.write({chunk});
Applied 'sendChunk'.

2025-02-19 20:44 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +public abstract class StreamResponse private constructor(public val data: HttpsCallableResult) {
I'll rename it to 'message'.

2025-02-19 20:45 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +      val callClient = options.apply(client)
Done.

2025-02-19 20:56 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +    val trimMargin: String
I'll rename it to errorMessage.

2025-02-19 21:52 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +              line.startsWith("data:") -> line.removePrefix("data:")
I'll Process line breaks inside the SSE streaming.

2025-02-19 22:09 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +public abstract class StreamResponse private constructor(public val data: HttpsCallableResult) {
Done.

2025-02-19 22:39 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +   * Messages are intermediate data chunks sent by the server before the final result.
Done.

2025-02-19 22:39 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/StreamResponse.kt
> +   * This result is sent as the last message in the stream and indicates that no further messages
I modified the kdoc to clarify the difference between two types.

2025-02-19 22:43 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * - if the request connected, but the function returned an error.
I corrected the kdoc.

2025-02-20 08:56 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +    subscriber.onSubscribe(
I will fix Subscription Handling: Ensure subscribe Does Not Trigger Backend Calls.

2025-02-20 08:56 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +        override fun request(n: Long) {
I'll take it into consideration.

2025-02-24 17:51 UTC, emilypgoogle commented on firebase-functions/api.txt
> +    method @NonNull public org.reactivestreams.Publisher stream(@Nullable Object data = null);
`./gradlew :firebase-functions:generateApiTxtFile`, the same run to generate these changes initially

2025-02-28 18:58 UTC, rlazo commented
Please, regenerate the api.txt file

2025-02-28 20:10 UTC, rlazo commented on firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
> +    Preconditions.checkNotNull(url, "url cannot be null")
given that the type is `URL` and not `URL?`, is this check necessary?

2025-02-28 20:10 UTC, rlazo commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +  public fun stream(): Publisher<StreamResponse> = stream(data = null)
we either make `Any?` into `Any` above, as this method covers the null scenario, or remove this and document what passing null means above.

2025-02-28 20:10 UTC, rlazo commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +            subscriber.onError(IllegalArgumentException("Requested messages must be positive."))
Don't forget that signalling onError terminates a subscription

https://github.com/reactive-streams/reactive-streams-jvm/tree/master?tab=readme-ov-file#1.6

2025-03-04 01:48 UTC, MustafaJadid2025 commented
> Please, regenerate the api.txt file

Done

2025-03-04 22:10 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +    subscribers.add(subscriber to requestedCount)
I made a new design and that implementation correctly rejects subscriptions when streaming has already completed. It allows new subscribers but only send future messages. This avoids memory overhead but can be confusing if messages were missed.

2025-03-04 22:10 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +            isStreamingStarted = true
Yes, but some actions need synchronization to avoid race conditions. Please check the new design.

2025-03-04 22:10 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +            subscriber.onError(IllegalArgumentException("Requested messages must be positive."))
Yes, in the current implementation, signaling onError() correctly terminates the subscription, ensuring that no further events are sent to the subscriber.

2025-03-05 19:24 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +            isStreamingStarted = true
I think some synchronization is excessive, like the private functions notifyComplete and notifyError which are only ever called from one thread that we already ensure is in charge, but the new design does address multithreading concerns.

2025-03-05 19:28 UTC, emilypgoogle approved these changes
Aside from my excessive synchronization comments which are non-blocking, all of my concerns were addressed and this seems to add the feature in line with reactive stream behavior expectations. @rlazo should make sure his concerns are also addressed

2025-03-05 20:16 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/PublisherStream.kt
> +            isStreamingStarted = true
Thanks for the comments. I remove excessive synchronization in methods notifyError, notifyComplete.

2025-03-05 23:12 UTC, ncooke3 commented on firebase-functions/src/androidTest/backend/functions/index.js
FYI, I've added a few extra tests in the iOS PR in case any seem important to test in this PR: https://github.com/firebase/firebase-ios-sdk/pull/14395/files#diff-1315c9d4cf741f276b99cb08dd88ef7096e852c05ff196b95cab75a96e21f778

2025-03-05 23:12 UTC, ncooke3 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&amp;lt;?&amp;gt;][java.util.List], where the contained objects are also one of these
Will `[List&amp;lt;?&amp;gt;]` appear in properly formatted way in Android studio?

2025-03-05 23:32 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&amp;lt;?&amp;gt;][java.util.List], where the contained objects are also one of these
It does not look good on the 'call' method either. Do we need to change both call and stream?

2025-03-05 23:35 UTC, ncooke3 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&amp;lt;?&amp;gt;][java.util.List], where the contained objects are also one of these
Yeah, these look like html entities. I'm guessing they can changed for `<` and `>`. cc: @emilypgoogle 
```suggestion
   * * [List&amp;lt;?&amp;gt;][java.util.List], where the contained objects are also one of these
```

2025-03-06 01:09 UTC, MustafaJadid2025 commented on firebase-functions/src/androidTest/backend/functions/index.js
I added test cases to cover genStreamEmpty, genStreamResultOnly, genStreamLargeData.

2025-03-10 13:46 UTC, thatfiredev commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +  public fun stream(data: Any? = null): Publisher<StreamResponse> {
We might want to annotate this function with [`@JvmOverloads`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.jvm/-jvm-overloads/) so that the compiler creates multiple methods for Java (`stream()` and `stream(Object data)`)

2025-03-10 14:47 UTC, rlazo commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +  public fun stream(data: Any? = null): Publisher<StreamResponse> {
+1

2025-03-10 19:46 UTC, rlazo approved these changes

2025-03-10 20:05 UTC, MustafaJadid2025 commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +  public fun stream(data: Any? = null): Publisher<StreamResponse> {
I added this annotation.

2025-03-10 20:30 UTC, emilypgoogle commented on firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
> +   * * [List&amp;lt;?&amp;gt;][java.util.List], where the contained objects are also one of these
I'll take a look after merging

2025-03-10 20:31 UTC, merged