Initial implementation to API spec
firebase/firebase-android-sdk pull request #6607
Opened 2024-12-18 19:16 UTC by davidmotson

Added support for querying imagen models to generate images both in gcs and inline. Documentation incoming in a separate PR for readability

2025-01-23 18:28 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +public class ImageModel
the refdocs and copyright headers are all in another PR to make this easier to review, and to make the refdocs easier for rachel to reivew.

2025-01-23 18:28 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGCSImage.kt
> +public class ImagenGCSImage(public val gcsUri: String, public val mimeType: String) {}
I don't believe so.

2025-01-23 18:29 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
> +  public val numberOfImages: Int? = 1,
Yes, this was actually discussed in the API doc, but we do want it to be nullable even if the default is 1, to differentiate between the user overriding our default in favor of the server default

2025-01-23 20:25 UTC, rlazo commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +public class ImageModel
The required `copyright check` will not pass without the headears. You can add refdocs in a follow up.

2025-01-23 20:31 UTC, rlazo commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
> +  public val numberOfImages: Int? = 1,
TBH I don't know if it would make sense for the devs to go from a known value (1) to an unknown (server default) but if it was discussed during API review, sgtm.

2025-01-24 17:37 UTC, davidmotson commented on firebase-vertexai/gradle.properties
> +version=17.0.0
No, not intended, was just used for testing, reverting

2025-01-27 17:55 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +public class ImageModel
The goal is not to submit this PR in this state, I'll merge the refdocs/copyright PR to *this* branch first.

2025-01-27 17:56 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +      "Unable to show generated images. All images were filtered out because they violated Vertex AI's usage guidelines. You will not be charged for blocked images. Try rephrasing the prompt. If you
This is a copy of the current message, We could remove that bit or change it however we want. Where would we want people to send this feedback?

2025-01-27 17:56 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
> +private fun GenerateImageResponse.validate() = apply {}
nope

2025-01-27 17:58 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
> +  ImagenInlineImage(bytesBase64Encoded!!.toByteArray(), mimeType!!)
Yes, this type has 3 values (mimetype, bytes, RAI filter reason, and gcs url) and the presence or absence of those types defines how we decode it. Before this point I've checked for the presence/absence of types and now it just needs to be decoded. 

This all has fairly good coverage in tests too.

2025-01-27 18:12 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/Request.kt
> +internal interface Request
I needed to subclass this in a different package. When we move the two together I can revert this.

2025-01-28 18:06 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
>  // TODO(rlazo): Add secondary constructor to pass through the message?
This TODO can be removed now

2025-01-28 18:16 UTC, daymxn requested changes
Left some comments, using the design doc as a reference- but otherwise LGTM.

Also, tbf, I'd prefer we got the docs in alongside this PR- just so it's easy to see in the diff if we missed anything. But it's not that big of a deal.

2025-01-28 18:16 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
> +  suspend fun generateImage(request: GenerateImageRequest): GenerateImageResponse =
Is there no streaming support for imagen yet?

2025-01-28 18:16 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
> +  public fun imageModel(
```suggestion
  public fun imagenModel(
```

2025-01-28 18:16 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +public class ImageModel
```suggestion
public class imagenModel
```

2025-01-28 18:16 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +  public suspend fun generateImage(prompt: String): ImagenGenerationResponse<ImagenInlineImage> =
```suggestion
  public suspend fun generateImages(prompt: String): ImagenGenerationResponse<ImagenInlineImage> =
```

2025-01-28 18:16 UTC, daymxn commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImageModel.kt
> +  public suspend fun generateImage(
```suggestion
  public suspend fun generateImages(
```

2025-01-28 18:24 UTC, davidmotson commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
> +  suspend fun generateImage(request: GenerateImageRequest): GenerateImageResponse =
correct

2025-01-28 18:53 UTC, rlazo commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
> +  ImagenInlineImage(bytesBase64Encoded!!.toByteArray(), mimeType!!)
Just to be super paranoic, could we check here that `bytesBase64Encoded` is not null and otherwise throw a `SerializationException` otherwise?

2025-01-28 18:54 UTC, rlazo commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
> +internal fun com.google.firebase.vertexai.internal.ImagenImageResponse.toPublicGCS() =
Same here, check and throw otherwise

2025-01-29 18:12 UTC, daymxn approved these changes

2025-02-04 20:01 UTC, rlazo approved these changes

2025-02-10 20:57 UTC, andrewheard commented on firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/Request.kt
> +    val includeRaiReason: Boolean?,
Would it be ever so slightly safer to make these non-optional so we never accidentally set them to `null`? I see they're explicitly set above
```
GenerateImageRequest.ImagenParameters(
  sampleCount = config?.numberOfImages ?: 1,
  includeRaiReason = true,
```
so I don't think you'd need to change the call site at all now. If we decide to change the behaviour in the future it'll force us to think harder about it if non-nullable.

2025-02-19 16:09 UTC, andrewheard approved these changes

2025-02-19 16:09 UTC, andrewheard commented on firebase-vertexai/CHANGELOG.md
> +* [feature] Added support for generating images with Imagen models.
As a heads up, this was the CHANGELOG entry I put in the Swift SDK. Consider adding the preview notes if it makes sense in the context of the Android release notes generation process: https://github.com/firebase/firebase-ios-sdk/blob/37b6456bdd9dc3e170d3eb0b9cf0cd9408f1a747/FirebaseVertexAI/CHANGELOG.md?plain=1#L2C1-L7C31

2025-02-19 16:11 UTC, davidmotson commented on firebase-vertexai/CHANGELOG.md
> +* [feature] Added support for generating images with Imagen models.
Ack

2025-02-19 16:11 UTC, merged